name: CI

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: latest
          extended: true

      - name: Build local ./exampleSite
        run: |
          ls
          cd ..
          echo 'rename to hugo-scroll as this is expected named of theme'
          mv site-web hugo-scroll
          cd hugo-scroll
          mkdir public
          hugo build --source=./exampleSite --themesDir=../.. --destination=../public
          echo 'rename back to original name for next tooling steps.'
          cp exampleSite CNAME public/
          cd ..
          mv hugo-scroll site-web
          cd site-web

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: atelier-des-ponts/atelier-des-ponts.github.io
          publish_branch: main
          publish_dir: ./public
